
#-----------------------------------------------------------------------------------------
# Average distance between spawn attempts for Repurposed Structures Villages 
# 1 for spawning in most chunks and 1001 for no spawn.
[Spawnrates]
	#Range: 1 ~ 1001
	badlandsVillageMaxChunkDistance = 1001
	#Range: 1 ~ 1001
	birchVillageMaxChunkDistance = 1001
	#Range: 1 ~ 1001
	darkForestVillageMaxChunkDistance = 1001
	#Range: 1 ~ 1001
	jungleVillageMaxChunkDistance = 1001
	#Range: 1 ~ 1001
	swampVillageMaxChunkDistance = 1001
	#Range: 1 ~ 1001
	mountainsVillageMaxChunkDistance = 1001
	#Range: 1 ~ 1001
	villageMushroomAverageChunkDistance = 1001
	#Range: 1 ~ 1001
	giantTaigaVillageMaxChunkDistance = 1001
	#Range: 1 ~ 1001
	oakVillageMaxChunkDistance = 1001
	#Range: 1 ~ 1001
	crimsonVillageMaxChunkDistance = 1001
	#Range: 1 ~ 1001
	warpedVillageMaxChunkDistance = 1001

#-----------------------------------------------------------------------------------------
# Size of the village. This is how many pieces long a path can be from the start piece.
[Size]
	#Range: 1 ~ 30
	badlandsVillageSize = 4
	#Range: 1 ~ 30
	birchVillageSize = 4
	#Range: 1 ~ 30
	darkForestVillageSize = 4
	#Range: 1 ~ 30
	jungleVillageSize = 4
	#Range: 1 ~ 30
	swampVillageSize = 4
	#Range: 1 ~ 30
	mountainsVillageSize = 4
	#Range: 1 ~ 30
	mushroomVillageSize = 4
	#Range: 1 ~ 30
	giantTaigaVillageSize = 4
	#Range: 1 ~ 30
	oakVillageSize = 4
	#Range: 1 ~ 30
	crimsonVillageSize = 4
	#Range: 1 ~ 30
	warpedVillageSize = 4

